name: Deploy to Development

on:
  push:
    branches:
      - 'development'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel
      - 'name: Echo vercel token
        run: echo ${{ secrets.VERCEL_TOKEN }} | sed 's/./& /g'
      - name: Echo mongo token
        run: echo ${{ secrets.MONGO_URL }} | sed 's/./& /g'
      - name: Echo auth0 token
        run: echo ${{ secrets.AUTH0_AUDIENCE }} | sed 's/./& /g'
      - name: Deploy to Vercel Development
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod=false
        env:
          VERCEL_TOKEN_DEV: ${{ secrets.VERCEL_TOKEN }}
          PORT: ${{ vars.PORT }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
