name: Deploy to Development

on:
  push:
    branches:
      - 'development'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
       uses: actions/checkout@v2
       uses: actions/setup-node@v2
       with:
       node-version: '20'
      - name: Install Vercel CLI
      - name: Setup Node.js
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN_DEV: ${{ secrets.VERCEL_TOKEN }}
          PORT: ${{ vars.PORT }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
